name: raw cargo build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  MY_DATA: test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Debug
      run: cargo build --verbose
    - name: Build Release
      run: cargo build --release --verbose
